<a href="https://colab.research.google.com/github/javierarteagapuell/deeplearning/blob/main/PRACTICA_Fashion_MNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [138]:
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np

s

In [139]:
from keras.datasets import fashion_mnist 

s

In [140]:
(train_data, train_labels), (test_data, test_labels) = fashion_mnist.load_data()

s

In [141]:
len(train_data)

60000

s

In [142]:
len(test_data)

10000

s

In [143]:
print(train_data.shape)
print(test_data.shape)

(60000, 28, 28)
(10000, 28, 28)


s

In [144]:
train_data = train_data.reshape((60000, 28 * 28))
print(train_data)
print(np.matrix(train_data[3000]))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[  0   0   0   0   0   0   0   0   1   1   0   0 120 131  91 147  30   0
    0   1   1   0   0   0   0   0   0   0   0   0   0   0   0   0   1   3
    0   0   0   0 251 199 172 195 152   0   0   0   0   3   1   0   0   0
    0   0   0   0   0   0   0   0   0   0   0  43 124 193 166 239 255 216
  172 228 126  61   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0  96 167 155 159 171 178 211 215 210 196 189 158 164 159 108   0   0
    0   0   0   0   0   0   0   0   0   0  83 157 131 117 120 148 148 145
  178 159 174 160 123 132 142 172  38   0   0   0   0   0   0   0   0   0
    0   0 159 128 118 120 122 112  93 124 161 109 128 128 129 146 138 167
  122   0   0   0   0   0   0   0   0   0   0   0 171 135 120 114 118 119
  107 125 123 117 124 124 119 145 147 166 148   0   0   0   0   0   0   0
    0   0   0   4 171 138 126 120 117 118 102 122 145 111 120 122 

s

In [145]:
train_data = train_data.astype('float32') / 255
train_data[3000]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.00392157, 0.00392157,
       0.        , 0.        , 0.47058824, 0.5137255 , 0.35686275,
       0.5764706 , 0.11764706, 0.        , 0.        , 0.00392157,
       0.00392157, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.00392157,
       0.01176471, 0.        , 0.        , 0.        , 0.        ,
       0.9843137 , 0.78039217, 0.6745098 , 0.7647059 , 0.59607846,
       0.        , 0.        , 0.        , 0.        , 0.01176471,
       0.00392157, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.16862746, 0.4862745 , 0.75686276, 0.6509804 , 0.9372549 ,
       1.        , 0.84705883, 0.6745098 , 0.89411765, 0.49411

s

In [146]:
test_data = train_data.astype('float32') / 255

s

In [147]:
from keras.utils.np_utils import to_categorical

one_hot_train_labels = to_categorical(train_labels)
one_hot_test_labels = to_categorical(test_labels)
one_hot_train_labels[30000]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=float32)

s

In [148]:
from tensorflow.keras import optimizers
from keras import losses
from keras import metrics
from keras import models
from keras import layers


model = models.Sequential()

#Capa 1
model.add(layers.Dense(10, activation='relu', name="Capa1",input_shape=(28*28,)))
model.compile(optimizer='sgd',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
#Capa 2
model.add(layers.Dense(10, name="Capa2",activation='relu'))
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
#Capa 3
model.add(layers.Dense(10, name="Capa3",activation='sigmoid'))
model.compile(optimizer='sgd',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
#Capa 4
model.add(layers.Dense(10, name="Capa4",activation='sigmoid'))
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
#Capa 5
model.add(layers.Dense(512, name="Capa5",activation='relu'))
model.compile(optimizer='sgd',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
#Capa 6
model.add(layers.Dense(512, name="Capa6",activation='relu'))
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
#Capa 7
model.add(layers.Dense(512, name="Capa7",activation='sigmoid'))
model.compile(optimizer='sgd',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
#Capa 8
model.add(layers.Dense(512, name="Capa8",activation='sigmoid'))
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
#Capa final
model.add(layers.Dense(10, name="CapaSalida",activation='softmax'))


s

In [149]:
model.summary()


Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 Capa1 (Dense)               (None, 10)                7850      
                                                                 
 Capa2 (Dense)               (None, 10)                110       
                                                                 
 Capa3 (Dense)               (None, 10)                110       
                                                                 
 Capa4 (Dense)               (None, 10)                110       
                                                                 
 Capa5 (Dense)               (None, 512)               5632      
                                                                 
 Capa6 (Dense)               (None, 512)               262656    
                                                                 
 Capa7 (Dense)               (None, 512)              

In [157]:
x_val = train_data[:10000]
partial_x_train = train_data[10000:]

y_val = one_hot_train_labels[:10000]
partial_y_train = one_hot_train_labels[10000:]

s

In [158]:
history = model.fit(train_data,
          train_labels,
          epochs=5,
          batch_size=128,
          validation_data=(x_val, y_val))

Epoch 1/5


ValueError: ignored

FALLA A PARTIR DE AQUI MIRAR!!!

In [ ]:
import matplotlib.pyplot as plt

loss = history.history['loss']

epochs = range(1, len(loss) + 1)

plt.plot(epochs, loss, 'bo', label='Pérdida del entreno')
plt.title('Perdidas del entreno y la validación')
plt.plot(epochs, val_acc, 'b', label='Precisión de validación')
plt.title('Perdidas del entreno y la validación')
plt.xlabel('Épocas')
plt.ylabel('Pérdida')
plt.legend()

plt.show()

s

In [ ]:
test_images[5]

s